[buildPlans.Purification]
family = "Purification"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Purification.variants]
  inherits = "ss05"

    [buildPlans.Purification.variants.design]
    two = "straight-neck-serifless"
    three = "two-arcs"
    four = "semi-open-serifless"
    five = "upright-arched-serifless"
    six = "straight-bar"
    seven = "bend-serifless-crossbar"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    zero = "oval-long-dotted"
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-h = "serifless"
    capital-i = "serifed"
    capital-k = "curly-serifless"
    capital-m = "hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-p = "open-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "curly-open-serifless"
    capital-t = "motion-serifed"
    capital-u = "toothless-corner-serifless"
    capital-v = "curly-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "curly-serifless"
    b = "toothed-serifless"
    d = "toothed-serifless"
    e = "rounded"
    f = "flat-hook-tailed"
    g = "double-storey"
    h = "straight-serifless"
    k = "curly-serifless"
    l = "serifed-semi-tailed"
    m = "short-leg-serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    r = "hookless-serifed"
    t = "bent-hook-asymmetric"
    v = "curly-serifless"
    w = "rounded-vertical-sides-flat-top-motion-serifed"
    x = "curly-serifless"
    y = "curly-turn-serifless"
    z = "curly-serifless"
    punctuation-dot = "round"
    ascii-single-quote = "raised-comma"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    guillemet = "curly"
    ampersand = "et-toothless-corner"
    percent = "rings-continuous-slash-also-connected"
    question = "smooth"
    pilcrow = "low"
    decorative-angle-brackets = "middle"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "with-notch"
    lig-single-arrow-bar = "with-notch"

  [buildPlans.Purification.ligations]
  inherits = "dlig"

[buildPlans.Purification.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Purification.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Purification.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Purification.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Purification.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Purification.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Purification.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Purification.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.Purification.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Purification.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
