[buildPlans.IosevkaSs05QuasiProportional]
family = "Iosevka SS05 Quasi-Proportional"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaSs05QuasiProportional.variants]
  inherits = "ss05"

[buildPlans.IosevkaSs05QuasiProportional.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaSs05QuasiProportional.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaSs05QuasiProportional.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaSs05QuasiProportional.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaSs05QuasiProportional.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaSs05QuasiProportional.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
