name: Run workflow.sh

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make workflow.sh executable
        run: chmod +x ./workflow.sh

      - name: Run workflow.sh
        run: ./workflow.sh

      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            COMMIT_MESSAGE="${COMMIT_MSG:-Apply changes from workflow.sh}"
            git commit -m "$COMMIT_MESSAGE"
            git push
          fi
