name: Build V8 Android ARM64

on:
  workflow_dispatch:

jobs:
  build-v8:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git curl build-essential ninja-build pkg-config

      - name: Setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "${GITHUB_WORKSPACE}/depot_tools" >> $GITHUB_PATH

      - name: Fetch V8
        run: |
          fetch v8
          cd v8
          git checkout 10.0.139.9
          gclient sync -D

      - name: Setup Android NDK
        run: |
          mkdir -p $HOME/.android-sdk-root/ndk
          cd $HOME/.android-sdk-root/ndk
          curl -L https://dl.google.com/android/repository/android-ndk-r27b-linux.zip -o ndk.zip
          unzip -q ndk.zip
          mv android-ndk-r27b 27.0.12077973
          rm ndk.zip

      - name: Configure GN
        run: |
          cd v8
          gn gen out/android_arm64 --args='
            target_os="android"
            target_cpu="arm64"
            v8_target_cpu="arm64"
            is_debug=false
            v8_monolithic=true
            v8_use_external_startup_data=false
            v8_enable_i18n_support=false
            v8_static_library=true
            android_ndk_root="'"$HOME/.android-sdk-root/ndk/27.0.12077973"'"
            android_api_level=26
            clang_use_chrome_plugins=false
            treat_warnings_as_errors=false
          '

      - name: Build V8
        run: |
          cd v8
          ninja -C out/android_arm64 v8_monolith

      - name: Upload headers
        uses: actions/upload-artifact@v4
        with:
          name: v8-headers
          path: v8/include

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: v8-lib
          path: v8/out/android_arm64/obj/libv8_monolith.a
